### ISSUE TITLE
用的是fis3打包方式，能不能直接script链接入页面

### ISSUE THREAD

**Issue by Baiang** [QingWei-Li/vuerify#1]
用的是fis3打包方式，能不能直接script链接入页面

**Comment by QingWei-Li** [comment]
可以，dist 里有打包成 umd 模式的
https://npmcdn.com/vuerify/dist/vuerify.js

**Comment by Baiang** [comment]
请问一个元素上绑定多个验证规则，这个支持吗？类似这种写法v-vuerify="['username','demo']"

**Comment by QingWei-Li** [comment]
@Baiang 目前不支持

**Comment by Baiang** [comment]
谢谢了
