### ISSUE TITLE
vue 2.2.1，parsePath变成undefined

### ISSUE THREAD

**Issue by ws456999** [QingWei-Li/vuerify#19]
新装vue 2.2.1，源码中parsePath变成undefined，导致this.$vuerify.check()不可用

**Comment by QingWei-Li** [comment]
`0.4.0` 已经修复了

**Comment by Niofh** [comment]
这个怎么解决 我都报错了!!!

**Comment by ws456999** [comment]
暂时先把vue降到2.1.8解决了

**Comment by QingWei-Li** [comment]
@ws456999 @Foreverofh 大佬们，有问题发代码贴错误信息啊，我测了就特么没问题啊 
https://jsfiddle.net/cinwell_li/w4n913o2/1/

**Comment by Niofh** [comment]
升级0.4.0没问题了
