### ISSUE TITLE
在低版本的android浏览器里报错

### ISSUE THREAD

**Issue by Leega0** [QingWei-Li/vuerify#23]
报错信息显示为：
Cannot use 'in' operator to search for 'default' in undefind at 
<img src="http://i4.buimg.com/4851/9cfc7b11582b0820.jpg">

**Comment by QingWei-Li** [comment]
看起来是 rollup 打包的问题

**Comment by Leega0** [comment]
猜测的原因已证实，android4.x版本不支持es6 object.assign,修改后正常
