### ISSUE TITLE
compouted 什么时候会触发执行

### ISSUE THREAD

**Issue by angusjiang** [QingWei-Li/vuerify#3]
compouted: {
    errors () {
      console.log(this.$vuerify.$errors);
      return this.$vuerify.$errors;
    }
  },
为什么我这边没有返回errors，只有check()的结果，这个方法根本没有执行啊，我得不到返回的错误信息。

**Comment by QingWei-Li** [comment]
麻烦提供下完整代码，也可以参考 demo 的做法。

**Comment by angusjiang** [comment]
配置：
// teacher 
var vue = require('vue');

var vueRouter = require('vue-router');
var vuerify = require('vuerify');

//初始化应用程序路由
vue.use(vueRouter);
vue.use(vuerify, {
	required: {
		test: /\s+/,
		message: '不能为空'
	}
});


html:
<div class="m-form text-left">
                                <label for="名称："></label>
                                <input v-cloak  placeholder="请输入小组名称"  v-model="addGroupName></input>
                                <ul><li v-for="err in errors" v-text="err"></li></ul> /*这里没有结果*/
                            </div>
js:
`import game from '../../common/game-modal.vue';
    export default{
        data(){
            return {
                'list': [],
                'groupCollection': { //global varibale of modify groupname
                    'oldName': '',
                    'newName': '',
                    'teamno': ''
                },
                'groupManage': {
                    'groupname': '',
                    'teamno': ''
                },
                'addGroupName': ''    
            }
        },

        vuerify: {
            addGroupName: {
                test: /\w{1,30}/,
                message: '小组名称由1-3-个字符组成'
            }
        },

        compouted: {
            errors() {
                console.log( this.$vuerify.$errors); //这里没有执行为什么
                return this.$vuerify.$errors;
            }
        },

        components: {
            game
        },

        methods:{
            //add group 
            addGroup() {
                var self = this;
                if (arguments.length === 0) {
                    $.popup('.popup-add-group');
                }else{
                    if (!self.$vuerify.check()) {
                        $('.comm-tips').addClass('comm-error');
                        return;
                    } else {
                        $('.comm-tips').removeClass('comm-error');
                        App.send('/api2/teacher_team/createTeam',{
                            data: {
                                'group_no': self.$route.params.groupId,
                                'name': self.addGroupName
                            },
                            type: 'post',
                            loadingBar: {
                                text:'添加中...'
                            },
                            success: function(result,isSuccess) {
                                if(isSuccess) {
                                    if (result.errcode === 0) {
                                        $.closeModal('.popup-add-group');
                                        self.refresh();
                                    };
                                }else{
                                }
                            }
                        });
                    }
                }
            }
        },

        created(){
            var self=this;
        },

        init(){

        }
    }`

**Comment by QingWei-Li** [comment]
Hi, 我根据你的代码弄了个简化版的，可以正常运行（ script 方式引入会自动执行 `Vue.use(vuerify)`)
https://jsbin.com/meyawo/edit?html,js,output

你粘贴的代码里 `v-model` 少一个引号，不知道是不是这个问题导致的
```html
<!-- v-model 少一个引号  -->
<input v-cloak  placeholder="请输入小组名称"  v-model="addGroupName></input>
```

**Comment by angusjiang** [comment]
不是因为引号，是我copy给你少了，你的DEMO是好的，我的还是不行，还有就是你的DOMO为什么可以做到只要input中的内容发生变化就触发校验，我是需要通过表单提交才触发的表单校验，是不是我们的vue版本不一样啊

**Comment by angusjiang** [comment]
我用的版本是1.0的

**Comment by QingWei-Li** [comment]
刚才测试过了, 1.0.0+ 都是支持的。同时我在本地建项目引入也是正常工作。你能否提供一份最小可复现 bug 的 demo 呢？

**Comment by QingWei-Li** [comment]
另外 input 不是闭合标签，不应该写作 `<input></input>` 在 HTML5 下应该写成 `<input >`
```html
<input v-cloak  placeholder="请输入小组名称"  v-model="addGroupName>
```
