### ISSUE TITLE
Cannot read property '$errors' of undefined

### ISSUE THREAD

**Issue by Undrizzle** [QingWei-Li/vuerify#4]
你好，我安装了v-vuerify-next，参照你的example,出现了Cannot read property '$errors' of undefined，$errors要自己定义吗？

**Comment by QingWei-Li** [comment]
https://github.com/QingWei-Li/vuerify/blob/master/examples/directive-next/entry.js
参照的这个 demo 么，vuerify 有定义么？

例如
```javascript
export default {
  data() {
    return { username: '' }
  },

  vuerify: { username: 'required' },

  computed: {
    error() {
      return this.$vuerify.$errors // vuerify 字段存在，才会注册 $vuerify 到实例上
    }
  }
}
```

**Comment by Undrizzle** [comment]
还是不行，是不是要绑定value啊
      <input type="text" placeholder="用户名" v-model="username" v-vuerify="username" @change="$emit('input', $event.target.value)">

export default {
        name: 'register-view',
        data () {
            return {
                username: ''
            }
        },
        vuerify: {
          username: {
              test: /\w{3,}/,
              message: '用户名至少为3位字符'
          }
        },
        computed: {
            errors () {
                return this.$vuerify.$errors
            }
        }
    }`

**Comment by QingWei-Li** [comment]
Vuerify 需要你自己注册，因为我是通过 script 标签引入的，已经自动注册了。所以你应该这么用
```javascript
import Vuerify from 'vuerify'
import Vue from 'vue'

Vue.use(Vuerify)

...
```

**Comment by Undrizzle** [comment]
谢谢，可以了。一个field能否添加两个验证规则呢，比如用户名长度为3到15个字符，小于3个字符和大于15个字符时分别为两个不同的message

**Comment by QingWei-Li** [comment]
还没支持

**Comment by QingWei-Li** [comment]
0.3.0 支持传入数组 https://github.com/QingWei-Li/vuerify/blob/master/examples/directive/entry.js#L41-L47
